### ISSUE TITLE
Delete all test issues (ones that aren't assigned to the project)

### ISSUE THREAD

**Issue by hickoryeyes** [Mdominykas/EncounterMe-name-subject-to-change#38]
Thank you, Dominykai

**Comment by Mdominykas** [comment]
> Thank you, Dominykai

I have no clue what it means, so will not be able to complete it

**Comment by hickoryeyes** [comment]
> > Thank you, Dominykai
> 
> I have no clue what it means, so will not be able to complete it

Oh... We meant these <33 
Since you're the repo owner you might have the permission to delete them.

![image](https://user-images.githubusercontent.com/73136801/135353440-2f78fbd6-449f-4c15-bc80-89cd78500b12.png)

**Comment by Mdominykas** [comment]
> > > Thank you, Dominykai
> > 
> > 
> > I have no clue what it means, so will not be able to complete it
> 
> Oh... We meant these <33 Since you're the repo owner you might have the permission to delete them.
> 
> ![image](https://user-images.githubusercontent.com/73136801/135353440-2f78fbd6-449f-4c15-bc80-89cd78500b12.png)

Oh... I see. Deleted them
